### ISSUE TITLE
Add binary release?

### ISSUE THREAD

**Issue by midwan** [segrax/directory_opus_amiga_plugin#2]
Hi @segrax 
I noticed you don't have any binary release yet, perhaps that would be a good idea?
Not everyone could/would compile it from source.

I've prepared one on my repo, for example: https://github.com/midwan/directory_opus_amiga_plugin/releases/tag/v1.0

I picked v1.0, since there doesn't seem to be any specific version string in the resulting DLL. Happy to adapt to something better, if you want.

**Comment by segrax** [comment]
Hey,

You're right, 
I was intending to put a binary in here, but decided to replace adflib first... then got side tracked and didn't do either :)
